### ISSUE TITLE
Feature: Find appimages as candidates on linux

### ISSUE THREAD

**Issue by IndianBoy42** [zyedidia/eget#1]
AppImages are good single file executables, convenient to install in the spirit of this tool I think \..

When I do `eget neovim/neovim` it doesn't consider the appimage [here](https://github.com/neovim/neovim/releases/tag/v0.5.0) to be a candidate

**Comment by zyedidia** [comment]
Appimages seem to match the spirit of this tool exactly so I have given them priority over other candidates for Linux systems. Eget will also now automatically rename `xxx.appimage` to `xxx` when extracting, but I'm not sure if this is a standard thing to do when using appimages. Running `eget neovim/neovim` now finds the appimage and extracts it to an executable `nvim` file. Let me know what you think.

**Comment by IndianBoy42** [comment]
Renaming seems like a good default

the `--to` flag let's you control the output name right?  That should be enough
