### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by j-lakeman** [zyedidia/eget#101]
Last commit was 6 months ago.
@zyedidia @hhromic @patinthehat @dufferzafar

**Comment by dufferzafar** [comment]
eget is stable. I use it every week to update a set of binaries that I have. I don't see any reason why it would need constant commits. There's nothing to maintain, really. 

If you're missing any particular feature, perhaps open a fresh issue, or better yet, a pull request?

**Comment by j-lakeman** [comment]
It is stable indeed but there are quite some bug reports open for quite some time, that's why I asked. Among them functionality-wise critical ones IMHO, like https://github.com/zyedidia/eget/issues/100 https://github.com/zyedidia/eget/issues/97 https://github.com/zyedidia/eget/issues/74 https://github.com/zyedidia/eget/issues/65 https://github.com/zyedidia/eget/issues/64.

**Comment by patinthehat** [comment]
While I'm unclear on the maintenance schedule of the project, I agree with @dufferzafar - the project is stable.  

It is also true that there are some bugs that need to be fixed and PR features that need to be merged, but in my experience the project is more than stable enough to rely on.

**Comment by zyedidia** [comment]
Yes, still maintained.
