### ISSUE TITLE
toml file blues: even the example from the manpage does not work

### ISSUE THREAD

**Issue by xkcd386at** [zyedidia/eget#102]
Here's a mostly self-explanatory transcript, using config file straight from the man page.  (Later I also tried expanding the "~" out, but no luck).

    # eget -v
    eget version 1.3.3

    # cat .eget.toml
    [global]
    to = "~/bin"

    ["zyedidia/micro"]
    to = "~/.local/bin"

    # eget --download-all
    2 matches found: please select manually
    (1) micro-2.0.13-linux64-static.tar.gz
    (2) micro-2.0.13-linux64.tar.gz
    Enter selection number: Error reading selection
    one or more errors occurred while downloading: [exit status 1]

OK so maybe the man page was written when there was only one candidate asset.  I added an asset filter and tried again:

    # cat .eget.toml
    [global]
    to = "~/bin"

    ["zyedidia/micro"]
    asset_filters = [ "static" ]
    to = "~/.local/bin"

    # eget --download-all
    https://github.com/zyedidia/micro/releases/download/v2.0.13/micro-2.0.13-linux64-static.tar.gz
    Downloading 100% [=======================================================================================] (4.6/4.6 MB, 5.246 MB/s)        
    Extracted `micro-2.0.13/micro` to `/root/micro`

And... it ignores both the "to" specs and puts the file in the current directory!

At this point I have to agree with #101 -- **if even the example from the man page does not work, what else can one infer**?

**Comment by zyedidia** [comment]
Sorry that was a mistake in the man page. It should be `target =` not `to =`.
