### ISSUE TITLE
Support for musl-based Releases

### ISSUE THREAD

**Issue by commiyou** [zyedidia/eget#105]
I am working on a CentOS 6.3 server, and the system’s built-in glibc doesn’t support GLIBC_2.34. So, is there a musl version of eget that can be released?

**Comment by zyedidia** [comment]
Could you elaborate on what you mean?

**Comment by benjaminbauer** [comment]
I guess the OP is referring to cases where binaries are provided for glibc and musl systems. e.g. https://github.com/sharkdp/fd/releases/tag/v10.1.0

When I `eget eget sharkdp/fd`, I have to chose if I want the musl or glibc version. 

It would be cool if eget could figure out on what kind of system it runs and pick accordingly, if there are multiple choices.

**Comment by dufferzafar** [comment]
@benjaminbauer eget already does system detection. There's no clear winner among libc/musl. You might want either depending on the conditions.

For cases where I know the musl build works fine, I usually do: `eget sharkdp/fd -a musl`

**Comment by benjaminbauer** [comment]
@dufferzafar for the majority of linux users/setups it is very clear if they are using musl or glibc, think debian or alpine. Only in a development setup one might have both present. I assume even then, the linker present in the path will use one or the other without explicit configuration.

**Comment by commiyou** [comment]
Sorry, I didn’t clearly explain my requirements. I am working on a CentOS 6.3 server, and the system’s built-in glibc doesn’t support GLIBC_2.34. So, is there a musl version of eget that can be released?

**Comment by zyedidia** [comment]
Ah, the builds are supposed to be made statically but it looks like in the latest release there was a problem, I will reupload a static version.

**Comment by zyedidia** [comment]
I just updated the 1.3.4 Linux AMD64 binary (the only non-static binary) on the releases page.
