### ISSUE TITLE
Feature Request: add installation option for binaries downloaded with `--download-only`

### ISSUE THREAD

**Issue by thorstenkampe** [zyedidia/eget#12]
It would make sense to add an option to "post-process" (extract) binaries that have been downloaded with `--download-only`.

This would implement a two-step installation process through which one could avoid the "403 Forbidden: API rate limit exceeded" error which is the topic of the still open issue #7 .

**Comment by zyedidia** [comment]
Isn't this what the tool already does when `--download-only` is not provided? Are you looking for some way to customize the extraction for things like `.deb` files? I also don't see how this avoids the API rate limit exceeded problem, since eget still has to make API requests to github to perform the download.

**Comment by thorstenkampe** [comment]
@zyedidia `eget` will not use an already downloaded file but - as you pointed out - download the file again from Github. What I have in mind is the following...

1. download files from Github on a machine which is able to download files from Github, distribute those files to multiple machines which are not able to download from Github. Install the packages on these machines via eget.
2. customizing the extraction the process is also one of my goals (install deb and rpm packages with `dpkg` and `yum`, extract everything else via `eget`)

**Comment by zyedidia** [comment]
Ah I see now. I think this is reasonable and will hopefully get to implementing it soon. My plan is to add support for supplying a local file instead of a repo/url and eget will skip the download phase and just extract it.
