### ISSUE TITLE
Feature: a flag to download pre release versions

### ISSUE THREAD

**Issue by IndianBoy42** [zyedidia/eget#2]
I don't know how possible this is, if you are using the GitHub API like I have for my own scripts, then there isn't a direct way to get the latest pre release, in the way that getting the latest release is built in.

This can be manually worked around using a tag (if the repo has provided it) but a direct way could be nice

**Comment by zyedidia** [comment]
Yes it doesn't seem like there is a latest pre-release tag built-in. Eget would have to read the releases information and then find the latest pre-release from that. I think this is doable.
