### ISSUE TITLE
[Question] Is there any way to upadate downloaded packages?

### ISSUE THREAD

**Issue by rjshrjndrn** [zyedidia/eget#21]
Hi,
Nice app. It's very useful. But one question, will eget handle updates of downloaded binaries?

**Comment by zyedidia** [comment]
Eget currently doesn’t track where binaries were downloaded from after the fact, so it can’t automatically update them. By default though eget downloads the latest release so if you rerun the download it may update if there is a new release.

**Comment by zyedidia** [comment]
See #14 and the new `--upgrade-only` flag, which approximates this in a useful way using the release creation date and the file modification date for the local file.
