### ISSUE TITLE
upgrade-only failure

### ISSUE THREAD

**Issue by leapfog** [zyedidia/eget#34]
seems using `--to` breaks `--upgrade-only`:

`$ eget --upgrade-only --to=$HOME/bin zyedidia/eget`

re-downloads eget (unless I already am in $HOME/bin)

**Comment by dufferzafar** [comment]
This is because `--upgrade-only` only checks for binaries in `$EGET_BIN`.

Can you try with `EGET_BIN=$HOME/bin eget --upgrade-only zyedidia/eget` ?

I personally have `export EGET_BIN` set, but I agree that users would expect `--to` to work with this as well.

Let me take a stab at this.

**Comment by leapfog** [comment]
You're right, after exporting `EGET_BIN=$HOME/bin`, there are no more re-downloads.

And yes, I would have expected that `--to` would work as well.

**Comment by dufferzafar** [comment]
@leapfog I've created a PR for this fix. 🙂
