### ISSUE TITLE
Install deb packages automatically

### ISSUE THREAD

**Issue by ngirard** [zyedidia/eget#39]
Using latest version of Eget on Ubuntu 21.10.

```sh
❯ eget --asset=deb --asset=amd64 cli/cli
https://github.com/cli/cli/releases/download/v2.11.3/gh_2.11.3_linux_amd64.deb
Downloading 100% [======================] (7.7/7.7 MB, 44.170 MB/s)        
Extracted `gh_2.11.3_linux_amd64.deb` to `gh_2.11.3_linux_amd64.deb`
```

In this scenario, it would be nice if Eget could automatically do the equivalent of `sudo dpkg -i ./gh_2.11.3_linux_amd64.deb && rm ./gh_2.11.3_linux_amd64.deb`.

Cheers

**Comment by dufferzafar** [comment]
I for one would _not_ want the install to happen, since I don't have sudo access on the box. I always download tarballs to avoid that. But this could go behind a feature flag.

**Comment by eadmaster** [comment]
Debs aren't the only package format to be supported, prolly better to generalize this with a list of delegates to be invoked (eg. rpm, appimage, flatpak, etc.)

**Comment by zyedidia** [comment]
I’m not sure there should be a special flag for automatically running package installers. You can use stdout to do this with something like `eget -q -a .deb -a amd64 cli/cli —to /dev/stdout | sudo dpkg -i /dev/stdin`

**Comment by indigoviolet** [comment]
@zyedidia Your suggestion doesn't work: `pkg: error: archive '/dev/stdin' is not a regular file` (https://askubuntu.com/a/170441)

**Comment by zyedidia** [comment]
Ah alright, I guess you'll have to create a temporary file: `eget -q -a .deb -a amd64 cli/cli --to /tmp/cli.deb && sudo dpkg -i /tmp/cli.deb`
