### ISSUE TITLE
[Bug] Release `v1.1.0`'s version number is incorrect when downloading source

### ISSUE THREAD

**Issue by superatomic** [zyedidia/eget#44]
The version number that is displayed when running `eget -v` on version `v1.1.0` shows the wrong version when building with `go build` or `go install`.

### Method 1

Run:

```shell
go install github.com/zyedidia/eget@v1.1.0
```

### Method 2

Download the [latest release (v1.1.0) zip](https://github.com/zyedidia/eget/archive/refs/tags/v1.1.0.zip) on the releases page.
Then, navigate to the directory with the zip file in it, and run:
```shell
unzip eget-1.1.0.zip
cd eget-1.1.0/
go install
```

### Result

Regardless of which method you used, run:

```shell
~/go/bin/eget -v
```

## Output
```
eget version 1.0.1+src
```

## Expected Output
```
eget version 1.1.0+src
```

## How to fix
It looks like the version number wasn't updated in [`version.go`](https://github.com/zyedidia/eget/blob/master/version.go). This should be able to be resolved by releasing a new `v1.1.1` release with the version number set correctly.

See also #31.

**Comment by zyedidia** [comment]
New version is released.
