### ISSUE TITLE
Add homebrew installation to the "How to get Eget" section

### ISSUE THREAD

**Issue by superatomic** [zyedidia/eget#45]
As of the successful merge of https://github.com/Homebrew/homebrew-core/pull/103276, Eget is now in the `homebrew-core` repository and can be installed by running:

```shell
brew install eget
```

I suggest that a "Homebrew" subsection is added to the ["How to get Eget" section of README.md](https://github.com/zyedidia/eget#how-to-get-eget).

If this issue is marked as `[pr-approved]`, I can write the subsection myself and submit a PR, if that would be helpful.

**Comment by zyedidia** [comment]
Thanks for adding eget to homebrew!
