### ISSUE TITLE
Remove some platform-specific suffixes

### ISSUE THREAD

**Issue by nikolay** [zyedidia/eget#47]
I tried to install https://github.com/editorconfig-checker/editorconfig-checker and it worked, but the binary carries some suffixes, which could be stripped off automatically: `ec-darwin-amd64`, i.e. the proper executable must be just `ec`.

**Comment by st0le** [comment]
I have this issue but I think it warrants a discussion whether it's an eget issue. The owner of the repo needs to ensure that the binary is named what is expected. 

That said, perhaps eget can have a flag that can "attempt" to rename files post extraction.  Best effort ofcourse.

**Comment by dufferzafar** [comment]
Yeah, attempting auto-rename would be a challenge, as there isn't a set naming convention.

Having a manual flag for renaming sounds good though, I currently have to `eget` & then `mv`

**Comment by zyedidia** [comment]
There is the `--to` flag. For example `eget editorconfig-checker/editorconfig-checker --to ec`.

**Comment by nikolay** [comment]
@zyedidia I thought `--to` always required a directory though, but now, after you clarified it, it makes sense. Thanks!
