### ISSUE TITLE
Add Chocolatey to the "How to get Eget" section in README.md

### ISSUE THREAD

**Issue by ksz16** [zyedidia/eget#55]
First of all, thank you very much for a development of this tool. Until now when I wanted to download binaries from GitHub in scripts I had to use a combination of curl and grep - Eget makes this task much simpler.
I thought that those miserable people using Windows (I'm kidding, of course :smiley:) also deserve an easy way to install Eget. So I created a package and added it to the [Chocolatey Community Repository](https://community.chocolatey.org/packages). Now Eget can be installed on Windows by running:

```
choco install eget
```

I made a pull request and added "Chocolatey" subsection to the "How to get Eget" section of README.md

**Comment by zyedidia** [comment]
Thanks!
