### ISSUE TITLE
Add a "tag pattern" parameter for repositories that host multiple packages

### ISSUE THREAD

**Issue by larsks** [zyedidia/eget#56]
I'd like to install `kustomize` from https://github.com/kubernetes-sigs/kustomize/releases, but this fails:

```
$ eget kubernetes-sigs/kustomize --to ~/bin
no candidates found
```

If I specify an explicit tag it works:

```
$ eget kubernetes-sigs/kustomize --to ~/bin/ -t kustomize/v4.5.7
https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v4.5.7/kustomize_v4.5.7_linux_amd64.tar.gz
Downloading 100% [=============================================================================================================================================================] (5.5/5.5 MB, 14.692 MB/s)
Extracted `kustomize` to `/home/lars/bin/kustomize`
```

It would be nice for this sort of repository if I could specify a tag *pattern*, so that I could run something like:

```
$ eget kubernetes-sigs/kustomize --to ~/bin --tag-pattern 'kustomize/.*'
```

And have `eget` get the latest release that matches the given tag pattern.

**Comment by patinthehat** [comment]
I've run into this issue as well, and would find this feature useful.

**Comment by zyedidia** [comment]
I suppose one solution might be to have the current tag to act as a "contains" match if it doesn't directly match anything. So if `-t kustomize` doesn't directly match a tag, then it will look for any tags that contain `kustomize` and take the most recent one.

**Comment by zyedidia** [comment]
This is now implemented as described above.
