### ISSUE TITLE
Allow downloading multiple assets from the same repository

### ISSUE THREAD

**Issue by larsks** [zyedidia/eget#57]
The operator-sdk project (https://github.com/operator-framework/operator-sdk) includes multiple binaries in each release:

- `ansible-operator`
- `helm-operator`
- `operator-sdk`

I'd like to be able to download all of them, but this doesn't work:

```
eget operator-framework/operator-sdk \
  -a operator-sdk_linux_amd64 \
  -a ansible-operator_linux_amd64
```

Nor does this:

```
eget operator-framework/operator-sdk -a operator-sdk_linux_amd64
eget operator-framework/operator-sdk -a ansible-operator_linux_amd64
```

**Comment by zyedidia** [comment]
Invoking eget multiple times (the second way you listed) should work fine -- what's the issue you are having with it?

**Comment by larsks** [comment]
Because the target filename is based on the repository name, running `eget` multiple times will in both instances download the artifact to the same local filename. But! I realize now that I was maybe misreading the documentation on the `--to` option -- I thought it was just a destination directory, but I see it can actually specify the target file, so I think that resolves this. Sorry for the noise!
