### ISSUE TITLE
eget 1.3.0 config file issues

### ISSUE THREAD

**Issue by leapfog** [zyedidia/eget#60]
From what I see when testing eget-1.3.0, https://github.com/zyedidia/eget#configuration shows an invalid config file: `to` should be `target`, as in `Example configuration` below, and `~` is **not** interpreted as the user's home but used litterally instead.

**Comment by rocketinventor** [comment]
Thanks for sharing @leapfog!

I also had this problem, and I found that switching the text from `to` to `target` does indeed help... Maybe submit a pull request?

**Comment by leapfog** [comment]
I don't think fcb8f1c fixed it: I cloned the repo, run make and have the same issue again. With the following config file
```
[global]
  target = "~/bin"
  upgrade_only = true
```
and the command `./eget zyedidia/eget` a directory named `~` is created and the eget-binary is placed inside, under the **name** `bin` (read: `bin` **is** the binary, not a directory with an eget binary inside!)

**Comment by zyedidia** [comment]
Oops, sorry about that. I think I've actually fixed it now. Thanks!

**Comment by leapfog** [comment]
Yes, it seems it's fixed now: All¹ my failed test do work now. (1: I only tested getting eget and micro.)
