### ISSUE TITLE
Working with monorepos

### ISSUE THREAD

**Issue by IgnisDa** [zyedidia/eget#67]
Hello, wonderful project!

I have [this](https://github.com/IgnisDa/rust-libs) single repository where I publish a bunch of binaries. I was wondering if it was possible to use eget with it. I do not think it, because eget only looks at the latest release.

Would it be possible to add an option to it to specify which binary to download? Something like `eget IgnisDa/rust-libs --someOption avatars_cli`. Then eget will look only for the latest releases matching `avatars_cli`.

You can see the release formats [here](https://github.com/IgnisDa/rust-libs/releases).

**Comment by zyedidia** [comment]
I think you can use the `tag` flag for this. If it does not match an exact tag then eget will look for the latest release with a tag that contains the given string.

**Comment by IgnisDa** [comment]
Alright that worked. Would be very helpful if the README has some info about using the `--tag` option for monorepos.
