### ISSUE TITLE
403 Forbidden: API rate limit exceeded

### ISSUE THREAD

**Issue by muralikodali** [zyedidia/eget#7]
I have got the following error :  

```
403 Forbidden: API rate limit exceeded for 183.82.157.82. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.): https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
```

**Comment by zyedidia** [comment]
GitHub has a rate limit for unauthenticated API requests: you can only make 60 per hour. I could add some authentication to eget which would allow you to raise this limit to 5000 per hour by providing a valid GitHub oauth token in the `GITHUB_TOKEN` environment variable. Currently the code implementing this is commented out in `download.go` due to being untested.

**Comment by thorstenkampe** [comment]
Any news on this?

**Comment by zyedidia** [comment]
I have pushed the update. Using `GITHUB_TOKEN` should now allow you to make more requests per hour.

**Comment by muralikodali** [comment]
after installing new version, problem subsided for two days and repeating again.

**Comment by zyedidia** [comment]
Have you set up a GitHub OAuth token? With the token you should not see this problem unless you are exceeding 5,000 requests per hour.

**Comment by muralikodali** [comment]
![screenshot_20211123115405](https://user-images.githubusercontent.com/11482766/142980150-b6b5a94f-63ef-436f-930b-f6abe53fdd3c.png)

I have also checked with wireshark to find out any requests are being made with github. there is no abnormal traffic to github.

**Comment by zyedidia** [comment]
Does the problem occur every time you use eget, or only in certain circumstances?

**Comment by muralikodali** [comment]
it occurs every time when using eget

**Comment by zyedidia** [comment]
I have pushed an update with a possible fix and a new option `--rate` which will display rate limiting information (total and remaining allowed requests) to help you diagnose the issue further.

**Comment by muralikodali** [comment]
thanks for the update.

it is now working without errors.

![small_screenshot_20211124171322](https://user-images.githubusercontent.com/11482766/143232686-6d468477-42fc-4a00-b496-c28f101c0b11.png)

**Comment by thorstenkampe** [comment]
I have the same problem with 0.3.0 - would you be able to make the fix available with a new release?

**Comment by zyedidia** [comment]
Yes no problem, I will release 0.3.1 later today.

**Comment by thorstenkampe** [comment]
`eget` uses now `GITHUB_TOKEN`. A side note: `--rate` seems mutually exclusive with all other options. Help for this option should make this explicit in my opinion.

**Comment by sochoaAtMulesoft** [comment]
Hey all.  Is there a reason why we're using `GITHUB_TOKEN` instead of `GIT_USER` and `GIT_PASS` ?
