### ISSUE TITLE
Support verify hash via config file

### ISSUE THREAD

**Issue by klutchell** [zyedidia/eget#71]
Is there any reason that the `--verify-sha256` option is only available via the CLI, and not the repo settings in configuration?

This tool is fantastic and I would love to use it for CI/CD but at the moment I have to call each package from my config individually with the `--verify-sha256` added instead of just `eget -D`.

**Comment by zyedidia** [comment]
Should be available now via `verify_sha256`

**Comment by klutchell** [comment]
This is working great, thanks for the quick turnaround!
